package blackbaud

import (
	"fmt"
	"strings"

	"github.com/amp-labs/connectors/common"
	"github.com/amp-labs/connectors/internal/components"
)

// nolint:funlen
func supportedOperations() components.EndpointRegistryInput {
	readSupport := []string{
		"crm-adnmg/businessprocessstatus",
		"crm-adnmg/batchtemplates",
		"crm-adnmg/currencies",
		"crm-adnmg/sites",
		"crm-adnmg/businessprocessinstances",
		"crm-adnmg/businessprocessparameterset",
		"crm-evtmg/registrationtypes",
		"crm-evtmg/registrants",
		"crm-evtmg/events",
		"crm-evtmg/locations",
		"crm-fndmg/designations/hierarchies",
		"crm-fndmg/fundraisingpurposes",
		"crm-fndmg/educationalhistory",
		"crm-fndmg/fundraisingpurposetypes",
		"crm-fndmg/fundraisingpurposerecipients",
		"crm-mktmg/correspondencecodes",
		"crm-mktmg/appeals",
		"crm-mktmg/segments/recordsources",
		"crm-mktmg/solicitcodes",
		"crm-prsmg/prospectmanagers",
		"crm-prsmg/prospectopportunities",
		"crm-prsmg/prospects",
		"crm-prsmg/stewardshipplansteps",
		"crm-revmg/payments",
		"crm-revmg/revenuetransactions",
		"crm-volmg/volunteerassignments",
		"crm-volmg/occurrences",
		"crm-volmgjobs",
		"crm-volmg/volunteers",
	}

	writeSupport := []string{
		"crm-adnmg/batches",
		"crm-adnmg/notifications",
		"crm-adnmg/batches/revenue",
		"crm-adnmg/businessprocess/launch",
		"crm-conmg/constituents",
		"crm-conmg/addresses",
		"crm-conmg/alternatelookupids",
		"crm-conmg/constituentappeals",
		"crm-conmg/constituentappealresponses",
		"crm-conmg/constituentattributes",
		"crm-conmg/constituentcorrespondencecodes",
		"crm-conmg/emailaddresses",
		"crm-conmg/fundraisers",
		"crm-conmg/interaction",
		"crm-conmg/constituentnotes",
		"crm-conmg/phones",
		"crm-conmg/solicitcodes",
		"crm-conmg/relationshipjobsinfo",
		"crm-conmg/tribute",
		"crm-conmg/educationalhistories",
		"crm-conmg/individuals",
		"crm-conmg/organizations",
		"crm-conmg/mergetwoconstituents",
		"crm-evtmg/events",
		"crm-evtmg/registrants",
		"crm-evtmg/registrationoptions",
		"crm-evtmg/registrationtypes",
		"crm-evtmg/locations",
		"crm-fndmg/fundraisingpurposes",
		"crm-fndmg/fundraisingpurposerecipients",
		"crm-mktmg/correspondencecodes",
		"crm-mktmg/appeals",
		"crm-mktmg/segments",
		"crm-mktmg/responsecategories",
		"crm-prsmg/prospects",
		"crm-prsmg/prospectsconstituency",
		"crm-prsmg/prospectcontactreports",
		"crm-prsmg/prospectsegmentations",
		"crm-prsmg/prospectopportunities",
		"crm-prsmg/prospectplans",
		"crm-prsmg/prospectsteps",
		"crm-prsmg/stewardshipplans",
		"crm-prsmg/stewardshipplansteps",
		"crm-revmg/recurringgifts",
		"crm-revmg/revenuenotes",
		"crm-revmg/payments",
		"crm-volmg/jobs",
		"crm-volmg/occurrences",
		"crm-volmg/timesheets",
		"crm-volmg/volunteers",
		"crm-volmg/volunteerschedules",
		"crm-volmg/volunteerassignments",
	}

	deleteSupport := []string{
		"crm-conmg/addresses",
		"crm-conmg/alternatelookupids",
		"crm-conmg/constituentappeals",
		"crm-conmg/constituentattributes",
		"crm-conmg/constituentcorrespondencecodes",
		"crm-conmg/emailaddresses",
		"crm-conmg/fundraisers",
		"crm-conmg/interaction",
		"crm-conmg/constituentnotes",
		"crm-conmg/phones",
		"crm-conmg/solicitcodes",
		"crm-conmg/relationshipjobsinfo",
		"crm-conmg/tribute",
		"crm-conmg/educationalhistories",
		"crm-evtmg/events",
		"crm-evtmg/registrants",
		"crm-evtmg/registrationoptions",
		"crm-evtmg/registrationtypes",
		"crm-evtmg/locations",
		"crm-fndmg/fundraisingpurposes",
		"crm-fndmg/fundraisingpurposerecipients",
		"crm-mktmg/correspondencecodes",
		"crm-mktmg/appeals",
		"crm-mktmg/segments",
		"crm-mktmg/responsecategories",
		"crm-prsmg/prospectsegmentations",
		"crm-prsmg/prospectopportunities",
		"crm-prsmg/prospectplans",
		"crm-prsmg/prospectsteps",
		"crm-prsmg/stewardshipplans",
		"crm-prsmg/stewardshipplansteps",
		"crm-revmg/payments",
		"crm-volmg/jobs",
		"crm-volmg/occurrences",
		"crm-volmg/timesheets",
		"crm-volmg/volunteers",
		"crm-volmg/volunteerassignments",
	}

	return components.EndpointRegistryInput{
		common.ModuleRoot: {
			{
				Endpoint: fmt.Sprintf("{%s}", strings.Join(readSupport, ",")),
				Support:  components.ReadSupport,
			},
			{
				Endpoint: fmt.Sprintf("{%s}", strings.Join(writeSupport, ",")),
				Support:  components.WriteSupport,
			},
			{
				Endpoint: fmt.Sprintf("{%s}", strings.Join(deleteSupport, ",")),
				Support:  components.DeleteSupport,
			},
		},
	}
}
