package main

import (
	"log/slog"
	"strings"

	"github.com/amp-labs/connectors/common"
	"github.com/amp-labs/connectors/common/naming"
	"github.com/amp-labs/connectors/internal/datautils"
	"github.com/amp-labs/connectors/internal/goutils"
	"github.com/amp-labs/connectors/internal/metadatadef"
	"github.com/amp-labs/connectors/internal/staticschema"
	"github.com/amp-labs/connectors/scripts/openapi/connectWise/internal/files"
	utilsopenapi "github.com/amp-labs/connectors/scripts/openapi/utils"
	"github.com/amp-labs/connectors/tools/fileconv/api3"
	"github.com/amp-labs/connectors/tools/scrapper"
)

// nolint:gochecknoglobals,lll
var (
	ignoreEndpoints = []string{
		// Schemas which hold MULTIPLE array properties
		"/company/companies/default",
		"/company/contacts/default",
		// Schemas that have NO array properties
		"/company/addressFormats/count",
		"/company/addressFormats/info/count",
		"/company/communicationTypes/count",
		"/company/communicationTypes/info/count",
		"/company/companies/count",
		"/company/companies/info/count",
		"/company/companies/info/types/count",
		"/company/companies/statuses/count",
		"/company/companies/types/count",
		"/company/companyPickerItems/count",
		"/company/companyTypeAssociations/count",
		"/company/configurations/count",
		"/company/configurations/statuses/count",
		"/company/configurations/statuses/info/count",
		"/company/configurations/types/count",
		"/company/contactTypeAssociations/count",
		"/company/contacts/count",
		"/company/contacts/departments/count",
		"/company/contacts/departments/info/count",
		"/company/contacts/info/count",
		"/company/contacts/relationships/count",
		"/company/contacts/types/count",
		"/company/contacts/types/count/info",
		"/company/countries/count",
		"/company/countries/info/count",
		"/company/entityTypes/count",
		"/company/entityTypes/info/count",
		"/company/expenseTypes/info/count",
		"/company/m365contact/count",
		"/company/m365contactsync/property/count",
		"/company/managedDevicesIntegrations/count",
		"/company/managedDevicesIntegrations/info/count",
		"/company/management/count",
		"/company/managementBackups/count",
		"/company/managementItSolutions/count",
		"/company/marketDescriptions/count",
		"/company/marketDescriptions/info/count",
		"/company/noteTypes/count",
		"/company/noteTypes/count/info",
		"/company/ownershipTypes/count",
		"/company/ownershipTypes/info/count",
		"/company/paymentTypes/info/count",
		"/company/portalConfigurations/count",
		"/company/portalConfigurations/invoiceSetup/paymentProcessors/count",
		"/company/portalSecurityLevels/count",
		"/company/portalSecuritySettings/count",
		"/company/states/count",
		"/company/states/info/count",
		"/company/teamRoles/count",
		"/company/teamRoles/info/count",
		"/company/tracks/count",
		"/configurations/types/info/count",
		"/expense/classifications/count",
		"/expense/entries/count",
		"/expense/info/taxTypes/count",
		"/expense/paymentTypes/count",
		"/expense/reports/count",
		"/expense/types/count",
		"/finance/accounting/batches/count",
		"/finance/accounting/unpostedPayments/count",
		"/finance/accounting/unpostedexpenses/count",
		"/finance/accounting/unpostedinvoices/count",
		"/finance/accounting/unpostedprocurement/count",
		"/finance/accountingPackageSetup/count",
		"/finance/accountingPackages/count",
		"/finance/agreements/count",
		"/finance/agreements/types/count",
		"/finance/agreements/types/info/count",
		"/finance/batchSetups/count",
		"/finance/billingCycles/count",
		"/finance/billingCycles/info/count",
		"/finance/billingSetups/count",
		"/finance/billingSetups/info/count",
		"/finance/billingStatuses/count",
		"/finance/billingStatuses/info/count",
		"/finance/billingTerms/count",
		"/finance/billingTerms/info/count",
		"/finance/companyFinance/count",
		"/finance/currencies/count",
		"/finance/currencies/info/count",
		"/finance/deliveryMethods/count",
		"/finance/glAccounts/count",
		"/finance/glAccounts/mappedTypes/count",
		"/finance/glCaptions/count",
		"/finance/glpaths/count",
		"/finance/info/currencyCodes/count",
		"/finance/info/taxIntegrations/count",
		"/finance/invoiceEmailTemplates/count",
		"/finance/invoiceEmailTemplates/info/count",
		"/finance/invoiceTemplateSetups/count",
		"/finance/invoiceTemplates/count",
		"/finance/invoices/count",
		"/finance/taxCodes/count",
		"/finance/taxCodes/info/count",
		"/finance/taxIntegrations/count",
		"/marketing/campaigns/count",
		"/marketing/campaigns/statuses/count",
		"/marketing/campaigns/subTypes/count",
		"/marketing/campaigns/types/count",
		"/marketing/campaigns/types/info/count",
		"/marketing/groups/count",
		"/marketing/groups/info/count",
		"/procurement/RMADispositions/count",
		"/procurement/RMADispositions/info/count",
		"/procurement/adjustments/count",
		"/procurement/adjustments/types/count",
		"/procurement/adjustments/types/info/count",
		"/procurement/catalog/count",
		"/procurement/catalog/info/count",
		"/procurement/categories/count",
		"/procurement/categories/info/count",
		"/procurement/changeorders/count",
		"/procurement/directionalSyncs/count",
		"/procurement/invoicegrouping/count",
		"/procurement/manufacturers/count",
		"/procurement/manufacturers/count/info",
		"/procurement/onhandserialnumbers/count",
		"/procurement/pricingschedules/count",
		"/procurement/products/count",
		"/procurement/purchaseorders/count",
		"/procurement/purchaseorders/info/count",
		"/procurement/purchaseorderstatuses/Info/count",
		"/procurement/purchaseorderstatuses/count",
		"/procurement/rmaActions/count",
		"/procurement/rmaActions/info/count",
		"/procurement/rmaStatuses/count",
		"/procurement/rmaStatuses/info/count",
		"/procurement/rmaTags/count",
		"/procurement/settings/count",
		"/procurement/shipmentmethods/count",
		"/procurement/shipmentmethods/info/count",
		"/procurement/subcategories/count",
		"/procurement/subcategories/info/count",
		"/procurement/types/count",
		"/procurement/types/info/count",
		"/procurement/unitOfMeasures/count",
		"/procurement/warehouseBins/count",
		"/procurement/warehouseBins/info/count",
		"/procurement/warehouses/count",
		"/procurement/warehouses/info/count",
		"/project/phaseStatuses/count",
		"/project/projectTemplates/count",
		"/project/projectTypes/count",
		"/project/projectTypes/info/count",
		"/project/projects/count",
		"/project/securityRoles/count",
		"/project/statusIndicators/count",
		"/project/statuses/count",
		"/project/statuses/info/count",
		"/project/tickets/count",
		"/sales/activities/count",
		"/sales/activities/statuses/count",
		"/sales/activities/statuses/info/count",
		"/sales/activities/types/count",
		"/sales/commissions/count",
		"/sales/opportunities/count",
		"/sales/opportunities/ratings/count",
		"/sales/opportunities/ratings/info/count",
		"/sales/opportunities/statuses/count",
		"/sales/opportunities/statuses/info/count",
		"/sales/opportunities/types/count",
		"/sales/opportunities/types/info/count",
		"/sales/orders/count",
		"/sales/orders/statuses/count",
		"/sales/orders/statuses/info/count",
		"/sales/probabilities/count",
		"/sales/probabilities/info/count",
		"/sales/quotas/count",
		"/sales/roles/count",
		"/sales/salesTeams/count",
		"/sales/schedule/holidaylists/info/count",
		"/sales/service/priority/info/count",
		"/sales/stages/count",
		"/sales/stages/info/count",
		"/schedule/calendars/count",
		"/schedule/calendars/info/count",
		"/schedule/colors/count",
		"/schedule/details/count",
		"/schedule/entries/count",
		"/schedule/holidayLists/count",
		"/schedule/portalcalendars/count",
		"/schedule/reminderTimes/count",
		"/schedule/statuses/count",
		"/schedule/statuses/info/count",
		"/schedule/types/count",
		"/schedule/types/info/count",
		"/service/SLAs/count",
		"/service/SLAs/info/count",
		"/service/boards/count",
		"/service/codes/count",
		"/service/emailTemplates/count",
		"/service/impacts/count",
		"/service/info/boards/count",
		"/service/info/boardtypes/count",
		"/service/knowledgeBaseArticles/count",
		"/service/knowledgeBaseCategories/count",
		"/service/knowledgeBaseSubCategories/count",
		"/service/knowledgebasesettings",
		"/service/locations/count",
		"/service/locations/info/count",
		"/service/priorities/count",
		"/service/scheduling/members/info/count",
		"/service/serviceSignoff/count",
		"/service/serviceSignoff/info/count",
		"/service/severities/count",
		"/service/sources/count",
		"/service/sources/info/count",
		"/service/surveys/count",
		"/service/teams/count",
		"/service/templates/count",
		"/service/templates/info/count",
		"/service/ticketLinks/count",
		"/service/ticketLinks/info/count",
		"/service/ticketSyncs/count",
		"/service/tickets/count",
		"/service/tickets/info/count",
		"/system/allowedfiletypes/count",
		"/system/allowedorigins/count",
		"/system/apiMembers/count",
		"/system/apiMembers/default",
		"/system/audittrail/count",
		"/system/authAnvils/count",
		"/system/authAnvils/testConnection",
		"/system/autoSyncTime/count",
		"/system/callbacks/count",
		"/system/certifications/count",
		"/system/connectWiseHostedScreens/count",
		"/system/connectwisehostedsetups/count",
		"/system/contactsync/monitoring/count",
		"/system/contactsync/monitoring/notificationtype/",
		"/system/customReports/count",
		"/system/cwTimeZones/count",
		"/system/departments/count",
		"/system/directionalSyncs/info/count",
		"/system/documentTypes/info/count",
		"/system/documents/count",
		"/system/ePayConfigurations/count",
		"/system/emailConnectors/count",
		"/system/emailConnectors/info/count",
		"/system/emailExclusions/count",
		"/system/emailTokens/count",
		"/system/experiments/count",
		"/system/fileuploadsettings/count",
		"/system/googleemailsetup/count",
		"/system/imaps/count",
		"/system/imaps/info/count",
		"/system/inOutBoards/count",
		"/system/inOutTypes/count",
		"/system/inOutTypes/count/info",
		"/system/info/departmentlocations/count",
		"/system/info/departments/count",
		"/system/info/links/count",
		"/system/info/locales/count",
		"/system/info/locations/count",
		"/system/info/members/count",
		"/system/info/personas/count",
		"/system/info/standardNotes/count",
		"/system/integratorTags/count",
		"/system/integratorlogins/count",
		"/system/kpiCategories/count",
		"/system/kpis/count",
		"/system/ldapConfigurations/count",
		"/system/ldapConfigurations/info/count",
		"/system/links/count",
		"/system/locations/count",
		"/system/m365contactsync/info/count",
		"/system/managementNetworkSecurities/count",
		"/system/members/count",
		"/system/members/types/count",
		"/system/members/types/info/count",
		"/system/membertemplates/count",
		"/system/menuentries/count",
		"/system/myCompany/corporateStructure/count",
		"/system/myCompany/corporateStructure/info/count",
		"/system/myCompany/corporateStructureLevels/count",
		"/system/myCompany/crm/count",
		"/system/myCompany/crm/info/count",
		"/system/myCompany/other/count",
		"/system/myCompany/timeExpense/count",
		"/system/myMembers",
		"/system/myMembers/info",
		"/system/notificationRecipients/count",
		"/system/office365/application/info/count",
		"/system/office365/emailSetups/count",
		"/system/onPremiseSearchSetting/count",
		"/system/osgradeweights/count",
		"/system/parsingTypes/count",
		"/system/parsingVariables/count",
		"/system/portalReports/count",
		"/system/quoteLinkSetup/count",
		"/system/quoteLinkSetup/testConnection",
		"/system/reportCards/count",
		"/system/reportCards/info/count",
		"/system/securityroles/count",
		"/system/securityroles/info/count",
		"/system/settings/count",
		"/system/setupScreens/count",
		"/system/skillCategories/count",
		"/system/skills/count",
		"/system/skills/info/count",
		"/system/ssoConfigurations/count",
		"/system/ssoUsers/count",
		"/system/standardNotes/count",
		"/system/surveys/count",
		"/system/surveys/info/count",
		"/system/timeZoneSetups/count",
		"/system/timeZoneSetups/info/count",
		"/system/todayPageCategories/count",
		"/system/todayPagelinks/count",
		"/system/userDefinedFields/count",
		"/system/userDefinedFields/info/count",
		"/system/workflows/count",
		"/system/workflows/tableTypes/count",
		"/system/workflows/tableTypes/info/count",
		"/time/accruals/count",
		"/time/activitystopwatches/count",
		"/time/chargeCodes/count",
		"/time/chargeCodes/info/count",
		"/time/entries/count",
		"/time/info/chargeCodeExpenseTypes/count",
		"/time/schedulestopwatches/count",
		"/time/sheets/count",
		"/time/ticketstopwatches/count",
		"/time/timePeriodSetups/count",
		"/time/timePeriodSetups/default",
		"/time/workRoles/count",
		"/time/workRoles/info/count",
		"/time/workTypes/count",
		"/time/workTypes/info/count",
		// Ignoring custom fields.
		"/procurement/rmaTags/default",
		"/sales/opportunities/default",
		// Conceptually not needed.
		"/system/info",
		"/system/reports",
		"/system/workflows/triggers/options",
		"/system/audittrail",
	}
	displayNameOverride = map[string]string{
		// "external": "External connections",
	}
)

func main() {
	schemas := staticschema.NewMetadata[staticschema.FieldMetadataMapV2]()
	registry := datautils.NamedLists[string]{}

	objects := Objects()
	for _, object := range objects {
		if object.Problem != nil {
			slog.Error("schema not extracted",
				"objectName", object.ObjectName,
				"error", object.Problem,
			)
		}

		for _, field := range object.Fields {
			schemas.Add(common.ModuleRoot, object.ObjectName, object.DisplayName, object.URLPath, object.ResponseKey,
				utilsopenapi.ConvertMetadataFieldToFieldMetadataMapV2(field), nil, object.Custom)
		}

		for _, queryParam := range object.QueryParams {
			registry.Add(queryParam, object.ObjectName)
		}
	}

	goutils.MustBeNil(files.OutputConnectWise.FlushSchemas(schemas))
	goutils.MustBeNil(files.OutputConnectWise.SaveQueryParamStats(scrapper.CalculateQueryParamStats(registry)))

	api3.PrintObjectsWithMultipleArrays()
	api3.PrintObjectsWithNoArrays()
	api3.PrintObjectsWithAutoSelectedArrays()

	slog.Info("Completed.")
}

func Objects() []metadatadef.Schema {
	explorer, err := files.InputConnectWise.GetExplorer(
		api3.WithDisplayNamePostProcessors(
			api3.SlashesToSpaceSeparated,
			api3.CamelCaseToSpaceSeparated,
			api3.CapitalizeFirstLetterEveryWord,
			collectionDisplayName,
		),
		api3.WithArrayItemAutoSelection(),
		api3.WithMediaType("application/vnd.connectwise.com+json; version=2025.16"),
	)
	goutils.MustBeNil(err)

	readObjects, err := explorer.ReadObjectsGet(
		api3.NewDenyPathStrategy(ignoreEndpoints),
		nil, displayNameOverride, nil,
	)
	goutils.MustBeNil(err)

	return readObjects
}

func collectionDisplayName(displayName string) string {
	collectionName, found := strings.CutPrefix(displayName, "Collection Of ")
	if !found {
		return displayName
	}

	return naming.NewPluralString(collectionName).String()
}
