version: v1.63.4
plugins:
  - module: 'github.com/amp-labs/connectors/tools/linters/nogoroutine'
    path: './tools/linters/nogoroutine'
  - module: 'github.com/amp-labs/connectors/tools/linters/modulelinter'
    path: './tools/linters/modulelinter'
