version: "2"
output:
  formats:
    text:
      path: stdout
linters:
  default: all
  disable:
    # Highly annoying. We'd need to whitelist all packages we import, which is a lot of work and adds very little value.
    - depguard
    # Annoying and unhelpful. Assumes uninitialized (zero-valued) fields are always a bug, which is plain wrong.
    - exhaustruct
    # Disabled because we use inits all over the place
    - gochecknoinits
    # Marks [TODO, FIXME, BUG] comments as errors. We use these, so this is not helpful - unless we decide this is a good policy.
    - godox
    # There are many legitimate cases for pre-allocating the length of a slice, so this is not helpful.
    - makezero
    # Buggy, it complains about unused nolint rules, when those nolint rules are actually used (and removing them cause other lint errors)
    - nolintlint
    # Named returns are helpful if there are multiple return values of the same type, and acts as self-documentation of the function.
    - nonamedreturns
    # Disabled because it enforces strict struct tag formatting that may conflict with provider-specific requirements
    - tagliatelle
    # We're not doing black-box testing, so enabling this would be counterproductive. We might want to discuss this though, it's a good practice.
    - testpackage
    # Annoying and not useful. Disabling otherwise we have to have comment everywhere
    - wrapcheck
  settings:
    # https://golangci-lint.run/docs/linters/configuration/#revive
    revive:
      rules:
        # Use var-naming, but add a special rule to accept "Id" rather than forcing "ID"
        - name: var-naming
          arguments:
            - - ID
              - API
          disabled: false
    # https://golangci-lint.run/docs/linters/configuration/#staticcheck
    staticcheck:
      checks:
        - all
        - -ST1003
    # https://golangci-lint.run/docs/linters/configuration/#varnamelen
    varnamelen:
      # The longest distance, in source lines, that is being considered a "small scope" where it is ok to use short variable names.
      # The default is 5, which is quite strict.
      max-distance: 10
    # Custom linters
    custom:
      modulelinter:
        type: module
        description: 'Checks module-related rules: DefaultModule, ModuleDependencies, and module constant naming (Module<ProviderName><ModuleName>)'
        settings: {}
      nogoroutine:
        type: module
        description: Detects bare 'go' keyword usage - use future.Go() or simultaneously.Do() instead
        settings:
          exclude-paths:
            - internal/future
            - internal/simultaneously
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: don't use ALL_CAPS in Go names
    paths:
      - playground
      - test
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - playground
      - test
      - third_party$
      - builtin$
      - examples$
