version: "2"
output:
  formats:
    text:
      path: stdout
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - gochecknoinits
    - godox
    - makezero
    - nolintlint
    - nonamedreturns
    - tagliatelle
    - testpackage
    - wrapcheck
  settings:
    revive:
      rules:
        - name: var-naming
          arguments:
            - - ID
              - API
          disabled: false
    staticcheck:
      checks:
        - all
        - -ST1003
    varnamelen:
      max-distance: 10
    custom:
      modulelinter:
        type: module
        description: 'Checks module-related rules: DefaultModule, ModuleDependencies, and module constant naming (Module<ProviderName><ModuleName>)'
        settings: {}
      nogoroutine:
        type: module
        description: Detects bare 'go' keyword usage - use future.Go() or simultaneously.Do() instead
        settings:
          exclude-paths:
            - internal/future
            - internal/simultaneously
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: don't use ALL_CAPS in Go names
    paths:
      - playground
      - test
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - playground
      - test
      - third_party$
      - builtin$
      - examples$
