package attio

import "time"

// objectData represents the common structure for object metadata
// returned by Attio API endpoints.
// Ref: https://docs.attio.com/rest-api/endpoint-reference/objects/list-objects#response-data
type objectData struct {
	Id struct {
		WorkspaceId string `json:"workspace_id"` //nolint:tagliatelle
		ObjectId    string `json:"object_id"`    //nolint:tagliatelle
	} `json:"id"`
	ApiSlug      string    `json:"api_slug"`      //nolint:tagliatelle
	SingularNoun string    `json:"singular_noun"` //nolint:tagliatelle
	PluralNoun   string    `json:"plural_noun"`   //nolint:tagliatelle
	CreatedAt    time.Time `json:"created_at"`    //nolint:tagliatelle
}

// objectResponse is used when the response returns a single object inside the data key.
type objectResponse struct {
	Data objectData `json:"data"`
}

// objectListResponse is used when the response returns a list (slice) of objects inside the data key.
type objectListResponse struct {
	Data []objectData `json:"data"`
}

type SubscriptionRequest struct {
	WebhookEndpoint string `json:"webhook_end_point" validate:"required"`
}

// subscriptionPayload is the payload structure for creating webhook subscriptions in Attio.
// Reference: https://docs.attio.com/rest-api/endpoint-reference/webhooks/create-a-webhook#body-data
type subscriptionPayload struct {
	Data subscriptionData `json:"data" validate:"required"`
}

type subscriptionData struct {
	TargetURL     string         `json:"target_url"    validate:"required"`
	Subscriptions []subscription `json:"subscriptions" validate:"required"`
}

type subscription struct {
	EventType providerEvent `json:"event_type" validate:"required"`
	// Filter is an object used to limit which webhook events are delivered.
	// Filters can target specific records (by list_id, entry_id) or specific object (by object_id).
	// It cannot be used to do field level filtering.
	// Use null to receive all events without filtering.
	// Ref: https://docs.attio.com/rest-api/guides/webhooks#filtering
	Filter any `json:"filter"`
}

// // createSubscriptionsResponse is the response returned by Attio when a webhook is created.
// Reference: https://docs.attio.com/rest-api/endpoint-reference/webhooks/create-a-webhook#response-data
type createSubscriptionsResponse struct {
	Data createSubscriptionsResponseData `json:"data"`
}

type createSubscriptionsResponseID struct {
	WorkspaceID string `json:"workspace_id"`
	WebhookID   string `json:"webhook_id"`
}

type createSubscriptionsResponseData struct {
	TargetURL     string                        `json:"target_url"`
	Subscriptions []subscription                `json:"subscriptions" validate:"required"`
	ID            createSubscriptionsResponseID `json:"id"`
	Status        string                        `json:"status"`
	CreatedAt     string                        `json:"created_at"`
	// Secret used for webhook signature verification.
	// Secret is generated by Attio and returned only during webhook creation.
	// Ref: https://docs.attio.com/rest-api/guides/webhooks#authenticating
	Secret string `json:"secret"`
}

// SuccessfulSubscription is used internally for rollback tracking.
type SuccessfulSubscription struct {
	ID         string
	ObjectName string
	EventName  string
}

type SubscriptionResult struct {
	Data createSubscriptionsResponseData `json:"data"`
}

// providerEvent represents the combined event type string used by Attio.
// A providerEvent value has the format "{objectName}.{eventAction}" (e.g., note.created", "task.updated").
type providerEvent string

type objectEvents struct {
	createEvents []providerEvent
	updateEvents []providerEvent
	deleteEvents []providerEvent
}
