package metadata

import (
	"archive/zip"
	"bytes"
	"encoding/xml"
	"errors"
	"fmt"
	"strings"

	"github.com/amp-labs/connectors/common"
	"github.com/amp-labs/connectors/providers/salesforce/internal/crm/core"
)

var (
	errWatchFieldsEmpty  = errors.New("watchFields must not be empty")
	errRequiredParamsMet = errors.New("objectName, triggerName, and indicatorFieldName are required")
	errEmptyObjectName   = errors.New("objectName must not be empty")
)

// ApexTriggerParams contains the parameters for constructing and deploying an APEX trigger.
type ApexTriggerParams struct {
	// ObjectName is the Salesforce object the trigger runs on (e.g., "Lead").
	ObjectName string

	// TriggerName is the name of the APEX trigger (e.g., "AmpersandTrack_Lead").
	// Use GenerateApexTriggerNameForCDC() or GenerateApexTriggerNameForRead() to generate this.
	TriggerName string

	// IndicatorField is the field definition for the indicator field that the trigger sets
	// when watched fields change. Supported types: boolean and datetime.
	IndicatorField common.FieldDefinition

	// WatchFields is the list of field API names to monitor for changes.
	WatchFields []string
}

// GenerateApexTriggerNameForCDC returns the APEX trigger name for CDC on a given Salesforce object.
func GenerateApexTriggerNameForCDC(objectName string) (string, error) {
	if objectName == "" {
		return "", errEmptyObjectName
	}

	return "CDC_" + objectName, nil
}

// GenerateApexTriggerNameForRead returns the APEX trigger name for filtered read on a given Salesforce object.
func GenerateApexTriggerNameForRead(objectName string) (string, error) {
	if objectName == "" {
		return "", errEmptyObjectName
	}

	return "Read_" + objectName, nil
}

// GenerateApexTestClassName returns the Apex test class name paired with a trigger.
// Salesforce production deploys with testLevel=RunSpecifiedTests require at least
// one test class executing the deployed Apex code with >=75% coverage; this is the
// canonical companion class generated by ConstructApexTrigger.
func GenerateApexTestClassName(triggerName string) (string, error) {
	if triggerName == "" {
		return "", errEmptyObjectName
	}

	return "Test_" + triggerName, nil
}

// ValidateApexTriggerParams checks that all required fields are present.
func ValidateApexTriggerParams(params ApexTriggerParams, indicatorFieldName string) error {
	if len(params.WatchFields) == 0 {
		return errWatchFieldsEmpty
	}

	if params.ObjectName == "" || params.TriggerName == "" || indicatorFieldName == "" {
		return errRequiredParamsMet
	}

	return nil
}

// ConstructApexTrigger builds the zip deployment package from pre-generated trigger code.
// It also bundles a generated companion Apex test class (Test_<TriggerName>) so the
// deploy can be validated under testLevel=RunSpecifiedTests, which Salesforce requires
// for production deploys (see Metadata API "DeployOptions" docs).
func ConstructApexTrigger(params ApexTriggerParams, triggerCode string) ([]byte, error) {
	triggerMetaXML := generateTriggerMetaXML()

	testClassName, err := GenerateApexTestClassName(params.TriggerName)
	if err != nil {
		return nil, err
	}

	testClassCode := generateTestClassCode(testClassName, params.ObjectName, params.WatchFields)
	testClassMetaXML := generateClassMetaXML()

	return createTriggerDeployZip(
		params.TriggerName, triggerCode, triggerMetaXML,
		testClassName, testClassCode, testClassMetaXML,
	)
}

// ConstructDestructiveApexTrigger builds a zipped destructive changes package to
// delete both the APEX trigger and its companion Test_<TriggerName> Apex class from
// Salesforce. The returned zip bytes are ready for DeployMetadataZip.
//
// The companion test class is removed alongside the trigger so the org is left
// clean after rollback. Because the destructive deploy can no longer point
// RunSpecifiedTests at a now-deleted class, callers should use testLevel=
// RunLocalTests (or NoTestRun in sandbox) for the rollback deploy.
func ConstructDestructiveApexTrigger(triggerName string) ([]byte, error) {
	testClassName, err := GenerateApexTestClassName(triggerName)
	if err != nil {
		return nil, err
	}

	return createTriggerDestructiveZip(triggerName, testClassName)
}

// GenerateTriggerCodeForCDC generates APEX trigger code that sets a boolean checkbox
// field to true/false based on whether any watched fields changed.
func GenerateTriggerCodeForCDC(params ApexTriggerParams, checkboxFieldName string) string {
	assignment := fmt.Sprintf("rec.%s = fieldChanged;", checkboxFieldName)

	return generateTriggerCode(params, assignment)
}

// GenerateTriggerCodeForFilteredRead generates APEX trigger code that sets a datetime
// field to System.now() when any watched fields change.
func GenerateTriggerCodeForFilteredRead(params ApexTriggerParams, timestampFieldName string) string {
	assignment := fmt.Sprintf(`if (fieldChanged) {
                rec.%s = System.now();
            }`, timestampFieldName)

	return generateTriggerCode(params, assignment)
}

// generateTriggerCode is the shared implementation that builds the APEX trigger code
// with a caller-provided indicator assignment snippet.
func generateTriggerCode(params ApexTriggerParams, indicatorAssignment string) string {
	// Build insert condition: field != null
	// We only check != null (not != '') because the empty-string check is invalid
	// for non-String Apex types (Boolean, Datetime, Number, etc.) and would cause
	// compilation errors. The null check is sufficient and type-safe for all field types.
	insertConditions := make([]string, 0, len(params.WatchFields))
	for _, field := range params.WatchFields {
		insertConditions = append(insertConditions,
			fmt.Sprintf("(rec.%s != null)", field))
	}

	insertExpr := strings.Join(insertConditions, " || ")

	// Build update condition: field changed compared to old record
	updateConditions := make([]string, 0, len(params.WatchFields))
	for _, field := range params.WatchFields {
		updateConditions = append(updateConditions,
			fmt.Sprintf("(rec.%s != oldRec.%s)", field, field))
	}

	updateExpr := strings.Join(updateConditions, " || ")

	return fmt.Sprintf(`trigger %s on %s (before insert, before update) {
    if (Trigger.isBefore) {
        for (%s rec : Trigger.new) {
            Boolean fieldChanged = false;

            if (Trigger.isInsert) {
                fieldChanged = %s;
            } else if (Trigger.isUpdate) {
                %s oldRec = Trigger.oldMap.get(rec.Id);
                fieldChanged = %s;
            }

            %s
        }
    }
}
`, params.TriggerName, params.ObjectName, params.ObjectName,
		insertExpr, params.ObjectName, updateExpr, indicatorAssignment)
}

func generateTriggerMetaXML() string {
	return fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<ApexTrigger xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>%s</apiVersion>
    <status>Active</status>
</ApexTrigger>
`, core.APIVersion)
}

func generateClassMetaXML() string {
	return fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<ApexClass xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>%s</apiVersion>
    <status>Active</status>
</ApexClass>
`, core.APIVersion)
}

// generateTestClassCode returns Apex test class source that exercises the trigger
// via DML on the target object. It populates required fields using runtime describe
// metadata, then performs an insert and (when insert succeeds) an update of a watched
// field. This covers both the BEFORE INSERT and BEFORE UPDATE branches of the trigger
// so Salesforce's 75% Apex code-coverage requirement is satisfied for production
// deploys using testLevel=RunSpecifiedTests.
//
// The class avoids assertions about indicator-field values so it remains valid both
// when the trigger is present and when the trigger has been removed while the test
// class is retained (the rollback path keeps test classes around so RunSpecifiedTests
// continues to have a runnable target).
func generateTestClassCode(testClassName, objectName string, watchFields []string) string {
	quoted := make([]string, 0, len(watchFields))
	for _, wf := range watchFields {
		quoted = append(quoted, "'"+strings.ReplaceAll(wf, "'", `\'`)+"'")
	}

	return fmt.Sprintf(apexTestClassTemplate, testClassName, objectName, strings.Join(quoted, ", "))
}

// apexTestClassTemplate is the Apex source for the generated companion test class.
// Placeholders (in order): test class name, object API name, comma-joined quoted watch fields.
const apexTestClassTemplate = `@isTest
private class %s {
    @isTest
    static void exerciseTrigger() {
        SObject rec = makeRec();
        Test.startTest();
        Database.SaveResult ins = Database.insert(rec, false);
        if (ins.isSuccess()) {
            mutateWatchField(rec);
            Database.update(rec, false);
        }
        Test.stopTest();
    }

    private static SObject makeRec() {
        Schema.SObjectType sot = Schema.getGlobalDescribe().get('%s');
        SObject rec = sot.newSObject();
        Map<String, Schema.SObjectField> fmap = sot.getDescribe().fields.getMap();
        for (String fname : fmap.keySet()) {
            Schema.DescribeFieldResult d = fmap.get(fname).getDescribe();
            if (!d.isCreateable() || d.isNillable() || d.isDefaultedOnCreate()) {
                continue;
            }
            try {
                rec.put(fname, dummyValue(d, 'init'));
            } catch (Exception e) {
                // Type mismatches tolerated; required-field coverage is best-effort.
            }
        }
        return rec;
    }

    private static void mutateWatchField(SObject rec) {
        Map<String, Schema.SObjectField> fmap = rec.getSObjectType().getDescribe().fields.getMap();
        for (String wf : new List<String>{%s}) {
            Schema.SObjectField sf = fmap.get(wf);
            if (sf == null) {
                continue;
            }
            try {
                rec.put(wf, dummyValue(sf.getDescribe(), 'mut'));
                return;
            } catch (Exception e) {
                // Try the next watch field on type mismatch.
            }
        }
    }

    private static Object dummyValue(Schema.DescribeFieldResult d, String tag) {
        Schema.DisplayType t = d.getType();
        if (t == Schema.DisplayType.EMAIL) {
            return 'amp+' + tag + '@example.com';
        }
        if (t == Schema.DisplayType.PHONE) {
            return '5551234567';
        }
        if (t == Schema.DisplayType.URL) {
            return 'https://example.com/' + tag;
        }
        if (t == Schema.DisplayType.STRING || t == Schema.DisplayType.TEXTAREA) {
            Integer len = d.getLength();
            String v = 'amp-' + tag;
            return (len > 0 && v.length() > len) ? v.substring(0, len) : v;
        }
        if (t == Schema.DisplayType.PICKLIST) {
            List<Schema.PicklistEntry> entries = d.getPicklistValues();
            return entries.isEmpty() ? null : entries[0].getValue();
        }
        if (t == Schema.DisplayType.BOOLEAN) {
            return true;
        }
        if (t == Schema.DisplayType.DATE) {
            return Date.today();
        }
        if (t == Schema.DisplayType.DATETIME) {
            return DateTime.now();
        }
        if (t == Schema.DisplayType.TIME) {
            return Time.newInstance(0, 0, 0, 0);
        }
        if (t == Schema.DisplayType.INTEGER) {
            return 1;
        }
        if (t == Schema.DisplayType.DOUBLE || t == Schema.DisplayType.PERCENT || t == Schema.DisplayType.CURRENCY) {
            return 1.0;
        }
        return null;
    }
}
`

// triggerPackageXML is the structure for Salesforce package.xml manifests.
type triggerPackageXML struct {
	XMLName xml.Name             `xml:"Package"`
	Xmlns   string               `xml:"xmlns,attr"`
	Types   []triggerPackageType `xml:"types"`
	Version string               `xml:"version"`
}

type triggerPackageType struct {
	Members []string `xml:"members"`
	Name    string   `xml:"name"`
}

func createTriggerDeployZip(
	triggerName, triggerCode, triggerMetaXML string,
	testClassName, testClassCode, testClassMetaXML string,
) ([]byte, error) {
	pkg := triggerPackageXML{
		Xmlns:   "http://soap.sforce.com/2006/04/metadata",
		Version: core.APIVersion,
		Types: []triggerPackageType{
			{
				Members: []string{triggerName},
				Name:    "ApexTrigger",
			},
			{
				Members: []string{testClassName},
				Name:    "ApexClass",
			},
		},
	}

	pkgXML, err := xml.MarshalIndent(pkg, "", "    ")
	if err != nil {
		return nil, fmt.Errorf("failed to marshal package.xml: %w", err)
	}

	var buf bytes.Buffer

	zipWriter := zip.NewWriter(&buf)

	if err := addTriggerToZip(zipWriter, "package.xml", []byte(xml.Header+string(pkgXML))); err != nil {
		return nil, err
	}

	if err := addTriggerToZip(zipWriter, "triggers/"+triggerName+".trigger", []byte(triggerCode)); err != nil {
		return nil, err
	}

	if err := addTriggerToZip(zipWriter, "triggers/"+triggerName+".trigger-meta.xml", []byte(triggerMetaXML)); err != nil {
		return nil, err
	}

	if err := addTriggerToZip(zipWriter, "classes/"+testClassName+".cls", []byte(testClassCode)); err != nil {
		return nil, err
	}

	if err := addTriggerToZip(zipWriter, "classes/"+testClassName+".cls-meta.xml", []byte(testClassMetaXML)); err != nil {
		return nil, err
	}

	if err := zipWriter.Close(); err != nil {
		return nil, fmt.Errorf("failed to close zip writer: %w", err)
	}

	return buf.Bytes(), nil
}

func createTriggerDestructiveZip(triggerName, testClassName string) ([]byte, error) {
	emptyPkg := triggerPackageXML{
		Xmlns:   "http://soap.sforce.com/2006/04/metadata",
		Version: core.APIVersion,
		Types:   []triggerPackageType{},
	}

	emptyPkgXML, err := xml.MarshalIndent(emptyPkg, "", "    ")
	if err != nil {
		return nil, fmt.Errorf("failed to marshal empty package.xml: %w", err)
	}

	destructivePkg := triggerPackageXML{
		Xmlns:   "http://soap.sforce.com/2006/04/metadata",
		Version: core.APIVersion,
		Types: []triggerPackageType{
			{
				Members: []string{triggerName},
				Name:    "ApexTrigger",
			},
			{
				Members: []string{testClassName},
				Name:    "ApexClass",
			},
		},
	}

	destructiveXML, err := xml.MarshalIndent(destructivePkg, "", "    ")
	if err != nil {
		return nil, fmt.Errorf("failed to marshal destructiveChanges.xml: %w", err)
	}

	var buf bytes.Buffer

	zipWriter := zip.NewWriter(&buf)

	if err := addTriggerToZip(zipWriter, "package.xml", []byte(xml.Header+string(emptyPkgXML))); err != nil {
		return nil, err
	}

	if err := addTriggerToZip(zipWriter, "destructiveChanges.xml", []byte(xml.Header+string(destructiveXML))); err != nil {
		return nil, err
	}

	if err := zipWriter.Close(); err != nil {
		return nil, fmt.Errorf("failed to close zip writer: %w", err)
	}

	return buf.Bytes(), nil
}

func addTriggerToZip(zw *zip.Writer, name string, content []byte) error {
	w, err := zw.Create(name)
	if err != nil {
		return fmt.Errorf("failed to create zip entry %s: %w", name, err)
	}

	if _, err := w.Write(content); err != nil {
		return fmt.Errorf("failed to write zip entry %s: %w", name, err)
	}

	return nil
}
