package facebook

import (
	"fmt"
	"strings"

	"github.com/amp-labs/connectors/internal/components"
)

// nolint:funlen
func supportedOperations() components.EndpointRegistryInput {
	readSupport := []string{
		"users",
		"ad_place_page_sets",
		"adrules_library",
		"adplayables",
		"adlabels",
		"adimages",
		"account_controls",
		"ads",
		"adsets",
		"advertisable_applications",
		"advideos",
		"applications",
		"broadtargetingcategories",
		"customaudiencestos",
		"customconversions",
		"deprecatedtargetingadsets",
		"dsa_recommendations",
		"impacting_ad_studies",
		"minimum_budgets",
		"promote_pages",
		"publisher_block_lists",
		"reachfrequencypredictions",
		"saved_audiences",
		"subscribed_apps",
		"targetingbrowse",
		"tracking",
		"adcreatives",
		"campaigns",
		"customaudiences",
		"ad_studies",
		"adnetworkanalytics_results",
		"adspixels",
		"business_invoices",
		"business_users",
		"client_pages",
		"client_pixels",
		"client_product_catalogs",
		"client_whatsapp_business_accounts",
		"clients",
		"collaborative_ads_collaboration_requests",
		"collaborative_ads_suggested_partners",
		"event_source_groups",
		"extendedcredits",
		"initiated_audience_sharing_requests",
		"managed_partner_ads_funding_source_details",
		"owned_apps",
		"owned_businesses",
		"owned_pages",
		"owned_pixels",
		"owned_product_catalogs",
		"owned_whatsapp_business_accounts",
		"pending_client_ad_accounts",
		"pending_client_apps",
		"pending_client_pages",
		"pending_owned_ad_accounts",
		"pending_owned_pages",
		"pending_users",
		"received_audience_sharing_requests",
		"system_users",
	}

	writeSupport := []string{
		"ad_place_page_sets",
		"adrules_library",
		"adplayables",
		"adlabels",
		"account_controls",
		"ad_place_page_sets_async",
		"ads",
		"adsets",
		"advideos",
		"customconversions",
		"product_audiences",
		"publisher_block_lists",
		"reachfrequencypredictions",
		"campaigns",
		"customaudiences",
		"adspixels",
		"assigned_users",
		"customaudiencestos",
		"subscribed_apps",
		"tracking",
		"adcreatives",
		"ad_studies",
		"adaccount",
		"adnetworkanalytics",
		"business_users",
		"event_source_groups",
		"owned_businesses",
		"owned_product_catalogs",
		"system_users",
		"owned_pages",
		"owned_apps",
		"owned_ad_accounts",
		"client_apps",
		"claim_custom_conversions",
		"china_business_onboarding_attributions",
	}

	return components.EndpointRegistryInput{
		"facebook": {
			{
				Endpoint: fmt.Sprintf("{%s}", strings.Join(readSupport, ",")),
				Support:  components.ReadSupport,
			},
			{
				Endpoint: fmt.Sprintf("{%s}", strings.Join(writeSupport, ",")),
				Support:  components.WriteSupport,
			},
		},
	}
}
