package highlevelstandard

import "github.com/amp-labs/connectors/internal/datautils"

const apiVersion = "2021-07-28"

var objectsWithLocationIdInParam = datautils.NewSet( //nolint:gochecknoglobals
	"businesses",
	"calendars",
	"calendars/groups",
	"campaigns",
	"conversations/search",
	"emails/schedule",
	"forms/submissions",
	"forms",
	"links",
	"blogs/authors",
	"blogs/categories",
	"funnels/lookup/redirect/list",
	"funnels/funnel/list",
	"opportunities/pipelines",
	"products",
	"proposals/document",
	"proposals/templates",
	"surveys",
	"users",
	"workflows",
)

var paginationObjects = datautils.NewSet( //nolint:gochecknoglobals
	"emails/schedule",
	"invoices",
	"invoices/template",
	"invoices/schedule",
	"invoices/estimate/list",
	"invoices/estimate/template",
	"blogs/authors",
	"blogs/categories",
	"funnels/lookup/redirect/list",
	"funnels/funnel/list",
	"payment/orders",
	"payments/transactions",
	"payments/subscriptions",
	"payments/coupon/list",
	"products",
	"products/inventory",
	"products/collections",
	"products/reviews",
	"store/shipping-zone",
	"locations/search",
	"custom-menus",
)

var objectWithAltTypeAndIdQueryParam = datautils.NewSet( //nolint:gochecknoglobals
	"invoices",
	"invoices/template",
	"invoices/schedule",
	"invoices/estimate/list",
	"invoices/estimate/template",
	"payments/orders",
	"payments/transactions",
	"payments/subscriptions",
	"payments/coupon/list",
	"products/inventory",
	"products/collections",
	"products/reviews",
	"store/shipping-zone",
	"store/shipping-carrier",
	"store/store-setting",
)

var objectWithSkipQueryParam = datautils.NewSet( //nolint:gochecknoglobals
	"custom-menus",
	"locations/search",
	"proposals/document",
	"proposals/templates",
	"surveys",
	"invoices",
)

var objectsNodePath = datautils.NewDefaultMap(map[string]string{ //nolint:gochecknoglobals
	"businesses":                   "businesses",
	"calendars":                    "calendars",
	"calendars/groups":             "groups",
	"campaigns":                    "campaigns",
	"conversations/search":         "conversations",
	"emails/schedule":              "schedules",
	"forms/submissions":            "submissions",
	"forms":                        "forms",
	"invoices":                     "invoices",
	"invoices/template":            "data",
	"invoices/schedule":            "schedules",
	"invoices/estimate/list":       "estimates",
	"invoices/estimate/template":   "data",
	"links":                        "links",
	"blogs/authors":                "authors",
	"blogs/categories":             "categories",
	"funnels/lookup/redirect/list": "data",
	"funnels/funnel/list":          "funnels",
	"opportunities/pipelines":      "pipelines",
	"payment/orders":               "data",
	"payments/transactions":        "data",
	"payments/subscriptions":       "data",
	"payments/coupon/list":         "data",
	"products":                     "products",
	"products/inventory":           "inventory",
	"products/collections":         "data",
	"products/reviews":             "data",
	"proposals/document":           "documents",
	"proposals/templates":          "data",
	"store/shipping-zone":          "data",
	"store/shipping-carrier":       "data",
	"store/store-setting":          "data",
	"snapshots":                    "snapshots",
	"surveys":                      "surveys",
	"users":                        "users ",
	"workflows":                    "workflows",
	"locations/search":             "locations",
	"custom-menus":                 "customMenus",
}, func(objectName string) string {
	return "id"
},
)
