{
  "openapi": "3.1.0",
  "info": {
    "title": "Harvest API",
    "version": "v3"
  },
  "servers": [
    {
      "url": "https://harvest.greenhouse.io"
    }
  ],
  "security": [
    {
      "bearer": []
    }
  ],
  "components": {
    "securitySchemes": {
      "basic_auth": {
        "description": "API Credential",
        "type": "http",
        "scheme": "basic"
      },
      "bearer": {
        "description": "JWT access_token from /auth/token",
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      },
      "oauth2": {
        "type": "oauth2",
        "description": "OAuth2 Authentication",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://auth.greenhouse.io/token",
            "scopes": {
              "harvest:application_stages:list": "List application stages",
              "harvest:applications:list": "List applications",
              "harvest:applications:destroy": "Destroy applications",
              "harvest:applications:create": "Create applications",
              "harvest:applications:update": "Update applications",
              "harvest:applications:hire": "Hire applications",
              "harvest:applications:convert_to_candidate": "Convert to candidate applications",
              "harvest:applications:reject": "Reject applications",
              "harvest:applications:unreject": "Unreject applications",
              "harvest:applications:move": "Move applications",
              "harvest:applied_candidate_tags:list": "List applied candidate tags",
              "harvest:applied_candidate_tags:create": "Create applied candidate tags",
              "harvest:applied_candidate_tags:destroy": "Destroy applied candidate tags",
              "harvest:approval_flows:list": "List approval flows",
              "harvest:approval_flows:create": "Create approval flows",
              "harvest:approval_flows:update": "Update approval flows",
              "harvest:approval_flows:request_approvals": "Request approvals",
              "harvest:approval_flows:replace_approver_groups": "Replace approver groups",
              "harvest:approver_groups:list": "List approver groups",
              "harvest:approver_groups:replace_approver": "Replace approvers",
              "harvest:approvers:list": "List approvers",
              "harvest:attachments:list": "List attachments",
              "harvest:attachments:create": "Create attachments",
              "harvest:attachments:destroy": "Destroy attachments",
              "harvest:blocked_spam_sources:list": "List blocked spam sources",
              "harvest:blocked_spam_sources:create": "Create blocked spam sources",
              "harvest:blocked_spam_sources:destroy": "Destroy blocked spam sources",
              "harvest:blocked_spam_sources:update": "Update blocked spam sources",
              "harvest:bulk_requests:list": "List bulk requests",
              "harvest:candidate_attribute_types:list": "List candidate attribute types",
              "harvest:candidate_educations:list": "List candidate educations",
              "harvest:candidate_educations:destroy": "Destroy candidate educations",
              "harvest:candidate_educations:create": "Create candidate educations",
              "harvest:candidate_employments:list": "List candidate employments",
              "harvest:candidate_employments:destroy": "Destroy candidate employments",
              "harvest:candidate_employments:create": "Create candidate employments",
              "harvest:candidate_tags:list": "List candidate tags",
              "harvest:candidate_tags:create": "Create candidate tags",
              "harvest:candidate_tags:destroy": "Destroy candidate tags",
              "harvest:candidates:list": "List candidates",
              "harvest:candidates:create": "Create candidates",
              "harvest:candidates:destroy": "Destroy candidates",
              "harvest:candidates:update": "Update candidates",
              "harvest:candidates:merge": "Merge candidates",
              "harvest:candidates:anonymize": "Anonymize candidates",
              "harvest:close_reasons:list": "List close reasons",
              "harvest:custom_field_departments:list": "List custom field departments",
              "harvest:custom_field_departments:create": "Create custom field departments",
              "harvest:custom_field_departments:destroy": "Destroy custom field departments",
              "harvest:custom_field_offices:list": "List custom field offices",
              "harvest:custom_field_offices:create": "Create custom field offices",
              "harvest:custom_field_offices:destroy": "Destroy custom field offices",
              "harvest:custom_field_options:list": "List custom field options",
              "harvest:custom_field_options:create": "Create custom field options",
              "harvest:custom_field_options:destroy": "Destroy custom field options",
              "harvest:custom_field_options:update": "Update custom field options",
              "harvest:custom_fields:list": "List custom fields",
              "harvest:custom_fields:destroy": "Destroy custom fields",
              "harvest:custom_fields:create": "Create custom fields",
              "harvest:custom_fields:update": "Update custom fields",
              "harvest:default_interviewers:list": "List default interviewers",
              "harvest:demographic_answer_options:list": "List demographic answer options",
              "harvest:demographic_answers:list": "List demographic answers",
              "harvest:demographic_question_sets:list": "List demographic question sets",
              "harvest:demographic_questions:list": "List demographic questions",
              "harvest:departments:list": "List departments",
              "harvest:departments:create": "Create departments",
              "harvest:departments:update": "Update departments",
              "harvest:eeoc:list": "List eeoc",
              "harvest:email_templates:list": "List email templates",
              "harvest:focus_candidate_attributes:list": "List focus candidate attributes",
              "harvest:future_job_permissions:list": "List future job permissions",
              "harvest:future_job_permissions:create": "Create future job permissions",
              "harvest:future_job_permissions:destroy": "Destroy future job permissions",
              "harvest:interview_kits:list": "List interview kits",
              "harvest:interviewer_tags:list": "List interviewer tags",
              "harvest:interviewers:list": "List interviewers",
              "harvest:interviews:list": "List interviews",
              "harvest:interviews:create": "Create interviews",
              "harvest:interviews:destroy": "Destroy interviews",
              "harvest:interviews:update": "Update interviews",
              "harvest:job_board_custom_locations:list": "List job board custom locations",
              "harvest:job_candidate_attributes:list": "List job candidate attributes",
              "harvest:job_hiring_managers:list": "List job hiring managers",
              "harvest:job_hiring_managers:create": "Create job hiring managers",
              "harvest:job_hiring_managers:destroy": "Destroy job hiring managers",
              "harvest:job_interview_stages:list": "List job interview stages",
              "harvest:job_interviews:list": "List job interviews",
              "harvest:job_notes:list": "List job notes",
              "harvest:job_notes:create": "Create job notes",
              "harvest:job_notes:destroy": "Destroy job notes",
              "harvest:job_notes:update": "Update job notes",
              "harvest:job_owners:list": "List job owners",
              "harvest:job_owners:create": "Create job owners",
              "harvest:job_owners:destroy": "Destroy job owners",
              "harvest:job_post_locations:list": "List job post locations",
              "harvest:job_post_locations:create": "Create job post locations",
              "harvest:job_post_locations:destroy": "Destroy job post locations",
              "harvest:job_posts:list": "List job posts",
              "harvest:job_posts:create": "Create job posts",
              "harvest:job_posts:update": "Update job posts",
              "harvest:jobs:list": "List jobs",
              "harvest:jobs:create": "Create jobs",
              "harvest:jobs:update": "Update jobs",
              "harvest:notes:list": "List notes",
              "harvest:notes:create": "Create notes",
              "harvest:offers:list": "List offers",
              "harvest:offers:create": "Create offers",
              "harvest:offers:update": "Update offers",
              "harvest:offices:list": "List offices",
              "harvest:offices:create": "Create offices",
              "harvest:offices:update": "Update offices",
              "harvest:openings:list": "List openings",
              "harvest:openings:create": "Create openings",
              "harvest:openings:destroy": "Destroy openings",
              "harvest:openings:update": "Update openings",
              "harvest:pay_input_ranges:list": "List pay input ranges",
              "harvest:pay_inputs:list": "List pay inputs",
              "harvest:prospect_details:list": "List prospect details",
              "harvest:prospect_pool_stages:list": "List prospect pool stages",
              "harvest:prospect_pools:list": "List prospect pools",
              "harvest:referrers:list": "List referrers",
              "harvest:rejection_details:list": "List rejection details",
              "harvest:rejection_details:update": "Update rejection details",
              "harvest:rejection_reasons:list": "List rejection reasons",
              "harvest:scorecard_candidate_attributes:list": "List scorecard candidate attributes",
              "harvest:scorecard_candidate_attributes:create": "Create scorecard candidate attributes",
              "harvest:scorecard_candidate_attributes:update": "Update scorecard candidate attributes",
              "harvest:scorecard_question_answer_options:create": "Create scorecard question answer options",
              "harvest:scorecard_question_answer_options:list": "List scorecard question answer options",
              "harvest:scorecard_question_answers:list": "List scorecard question answers",
              "harvest:scorecard_question_answers:create": "Create scorecard question answers",
              "harvest:scorecard_question_answers:update": "Update scorecard question answers",
              "harvest:scorecard_question_candidate_attributes:list": "List scorecard question candidate attributes",
              "harvest:scorecard_question_options:list": "List scorecard question options",
              "harvest:scorecard_questions:list": "List scorecard questions",
              "harvest:scorecards:list": "List scorecards",
              "harvest:scorecards:create": "Create scorecards",
              "harvest:scorecards:update": "Update scorecards",
              "harvest:sources:list": "List sources",
              "harvest:tracking_links:list": "List tracking links",
              "harvest:user_emails:list": "List user emails",
              "harvest:user_emails:create": "Create user emails",
              "harvest:user_job_permissions:list": "List user job permissions",
              "harvest:user_job_permissions:create": "Create user job permissions",
              "harvest:user_job_permissions:destroy": "Destroy user job permissions",
              "harvest:user_roles:list": "List user roles",
              "harvest:users:list": "List users",
              "harvest:users:create": "Create users",
              "harvest:users:update": "Update users",
              "harvest:users:deactivate": "Deactivate users",
              "harvest:users:activate": "Activate users",
              "harvest:users:revoke_permissions": "Revoke permissions users",
              "harvest:webhooks:create": "Create webhooks",
              "harvest:webhooks:update": "Update webhooks",
              "harvest:webhooks:destroy": "Destroy webhooks",
              "harvest:webhooks:list": "List webhooks",
              "auditlog:events:list": "List audit log events"
            }
          },
          "authorizationCode": {
            "authorizationUrl": "https://auth.greenhouse.io/authorize",
            "tokenUrl": "https://auth.greenhouse.io/token",
            "refreshUrl": "https://auth.greenhouse.io/token",
            "scopes": {
              "harvest:application_stages:list": "List application stages",
              "harvest:applications:list": "List applications",
              "harvest:applications:destroy": "Destroy applications",
              "harvest:applications:create": "Create applications",
              "harvest:applications:update": "Update applications",
              "harvest:applications:hire": "Hire applications",
              "harvest:applications:convert_to_candidate": "Convert to candidate applications",
              "harvest:applications:reject": "Reject applications",
              "harvest:applications:unreject": "Unreject applications",
              "harvest:applications:move": "Move applications",
              "harvest:applied_candidate_tags:list": "List applied candidate tags",
              "harvest:applied_candidate_tags:create": "Create applied candidate tags",
              "harvest:applied_candidate_tags:destroy": "Destroy applied candidate tags",
              "harvest:approval_flows:list": "List approval flows",
              "harvest:approval_flows:create": "Create approval flows",
              "harvest:approval_flows:update": "Update approval flows",
              "harvest:approval_flows:request_approvals": "Request approvals",
              "harvest:approval_flows:replace_approver_groups": "Replace approver groups",
              "harvest:approver_groups:list": "List approver groups",
              "harvest:approver_groups:replace_approver": "Replace approvers",
              "harvest:approvers:list": "List approvers",
              "harvest:attachments:list": "List attachments",
              "harvest:attachments:create": "Create attachments",
              "harvest:attachments:destroy": "Destroy attachments",
              "harvest:blocked_spam_sources:list": "List blocked spam sources",
              "harvest:blocked_spam_sources:create": "Create blocked spam sources",
              "harvest:blocked_spam_sources:destroy": "Destroy blocked spam sources",
              "harvest:blocked_spam_sources:update": "Update blocked spam sources",
              "harvest:bulk_requests:list": "List bulk requests",
              "harvest:candidate_attribute_types:list": "List candidate attribute types",
              "harvest:candidate_educations:list": "List candidate educations",
              "harvest:candidate_educations:destroy": "Destroy candidate educations",
              "harvest:candidate_educations:create": "Create candidate educations",
              "harvest:candidate_employments:list": "List candidate employments",
              "harvest:candidate_employments:destroy": "Destroy candidate employments",
              "harvest:candidate_employments:create": "Create candidate employments",
              "harvest:candidate_tags:list": "List candidate tags",
              "harvest:candidate_tags:create": "Create candidate tags",
              "harvest:candidate_tags:destroy": "Destroy candidate tags",
              "harvest:candidates:list": "List candidates",
              "harvest:candidates:create": "Create candidates",
              "harvest:candidates:destroy": "Destroy candidates",
              "harvest:candidates:update": "Update candidates",
              "harvest:candidates:merge": "Merge candidates",
              "harvest:candidates:anonymize": "Anonymize candidates",
              "harvest:close_reasons:list": "List close reasons",
              "harvest:custom_field_departments:list": "List custom field departments",
              "harvest:custom_field_departments:create": "Create custom field departments",
              "harvest:custom_field_departments:destroy": "Destroy custom field departments",
              "harvest:custom_field_offices:list": "List custom field offices",
              "harvest:custom_field_offices:create": "Create custom field offices",
              "harvest:custom_field_offices:destroy": "Destroy custom field offices",
              "harvest:custom_field_options:list": "List custom field options",
              "harvest:custom_field_options:create": "Create custom field options",
              "harvest:custom_field_options:destroy": "Destroy custom field options",
              "harvest:custom_field_options:update": "Update custom field options",
              "harvest:custom_fields:list": "List custom fields",
              "harvest:custom_fields:destroy": "Destroy custom fields",
              "harvest:custom_fields:create": "Create custom fields",
              "harvest:custom_fields:update": "Update custom fields",
              "harvest:default_interviewers:list": "List default interviewers",
              "harvest:demographic_answer_options:list": "List demographic answer options",
              "harvest:demographic_answers:list": "List demographic answers",
              "harvest:demographic_question_sets:list": "List demographic question sets",
              "harvest:demographic_questions:list": "List demographic questions",
              "harvest:departments:list": "List departments",
              "harvest:departments:create": "Create departments",
              "harvest:departments:update": "Update departments",
              "harvest:eeoc:list": "List eeoc",
              "harvest:email_templates:list": "List email templates",
              "harvest:focus_candidate_attributes:list": "List focus candidate attributes",
              "harvest:future_job_permissions:list": "List future job permissions",
              "harvest:future_job_permissions:create": "Create future job permissions",
              "harvest:future_job_permissions:destroy": "Destroy future job permissions",
              "harvest:interview_kits:list": "List interview kits",
              "harvest:interviewer_tags:list": "List interviewer tags",
              "harvest:interviewers:list": "List interviewers",
              "harvest:interviews:list": "List interviews",
              "harvest:interviews:create": "Create interviews",
              "harvest:interviews:destroy": "Destroy interviews",
              "harvest:interviews:update": "Update interviews",
              "harvest:job_board_custom_locations:list": "List job board custom locations",
              "harvest:job_candidate_attributes:list": "List job candidate attributes",
              "harvest:job_hiring_managers:list": "List job hiring managers",
              "harvest:job_hiring_managers:create": "Create job hiring managers",
              "harvest:job_hiring_managers:destroy": "Destroy job hiring managers",
              "harvest:job_interview_stages:list": "List job interview stages",
              "harvest:job_interviews:list": "List job interviews",
              "harvest:job_notes:list": "List job notes",
              "harvest:job_notes:create": "Create job notes",
              "harvest:job_notes:destroy": "Destroy job notes",
              "harvest:job_notes:update": "Update job notes",
              "harvest:job_owners:list": "List job owners",
              "harvest:job_owners:create": "Create job owners",
              "harvest:job_owners:destroy": "Destroy job owners",
              "harvest:job_post_locations:list": "List job post locations",
              "harvest:job_post_locations:create": "Create job post locations",
              "harvest:job_post_locations:destroy": "Destroy job post locations",
              "harvest:job_posts:list": "List job posts",
              "harvest:job_posts:create": "Create job posts",
              "harvest:job_posts:update": "Update job posts",
              "harvest:jobs:list": "List jobs",
              "harvest:jobs:create": "Create jobs",
              "harvest:jobs:update": "Update jobs",
              "harvest:notes:list": "List notes",
              "harvest:notes:create": "Create notes",
              "harvest:offers:list": "List offers",
              "harvest:offers:create": "Create offers",
              "harvest:offers:update": "Update offers",
              "harvest:offices:list": "List offices",
              "harvest:offices:create": "Create offices",
              "harvest:offices:update": "Update offices",
              "harvest:openings:list": "List openings",
              "harvest:openings:create": "Create openings",
              "harvest:openings:destroy": "Destroy openings",
              "harvest:openings:update": "Update openings",
              "harvest:pay_input_ranges:list": "List pay input ranges",
              "harvest:pay_inputs:list": "List pay inputs",
              "harvest:prospect_details:list": "List prospect details",
              "harvest:prospect_pool_stages:list": "List prospect pool stages",
              "harvest:prospect_pools:list": "List prospect pools",
              "harvest:referrers:list": "List referrers",
              "harvest:rejection_details:list": "List rejection details",
              "harvest:rejection_details:update": "Update rejection details",
              "harvest:rejection_reasons:list": "List rejection reasons",
              "harvest:scorecard_candidate_attributes:list": "List scorecard candidate attributes",
              "harvest:scorecard_candidate_attributes:create": "Create scorecard candidate attributes",
              "harvest:scorecard_candidate_attributes:update": "Update scorecard candidate attributes",
              "harvest:scorecard_question_answer_options:create": "Create scorecard question answer options",
              "harvest:scorecard_question_answer_options:list": "List scorecard question answer options",
              "harvest:scorecard_question_answers:list": "List scorecard question answers",
              "harvest:scorecard_question_answers:create": "Create scorecard question answers",
              "harvest:scorecard_question_answers:update": "Update scorecard question answers",
              "harvest:scorecard_question_candidate_attributes:list": "List scorecard question candidate attributes",
              "harvest:scorecard_question_options:list": "List scorecard question options",
              "harvest:scorecard_questions:list": "List scorecard questions",
              "harvest:scorecards:list": "List scorecards",
              "harvest:scorecards:create": "Create scorecards",
              "harvest:scorecards:update": "Update scorecards",
              "harvest:sources:list": "List sources",
              "harvest:tracking_links:list": "List tracking links",
              "harvest:user_emails:list": "List user emails",
              "harvest:user_emails:create": "Create user emails",
              "harvest:user_job_permissions:list": "List user job permissions",
              "harvest:user_job_permissions:create": "Create user job permissions",
              "harvest:user_job_permissions:destroy": "Destroy user job permissions",
              "harvest:user_roles:list": "List user roles",
              "harvest:users:list": "List users",
              "harvest:users:create": "Create users",
              "harvest:users:update": "Update users",
              "harvest:users:deactivate": "Deactivate users",
              "harvest:users:activate": "Activate users",
              "harvest:users:revoke_permissions": "Revoke permissions users",
              "harvest:webhooks:create": "Create webhooks",
              "harvest:webhooks:update": "Update webhooks",
              "harvest:webhooks:destroy": "Destroy webhooks",
              "harvest:webhooks:list": "List webhooks",
              "auditlog:events:list": "List audit log events"
            }
          }
        }
      }
    }
  },
  "paths": {
    "/auth/token": {
      "post": {
        "summary": "generate access_token",
        "tags": [
          "Access Token"
        ],
        "security": [
          {
            "basic_auth": []
          }
        ]
      }
    },
    "/v3/application_stages": {
      "get": {
        "summary": "List application stages",
        "tags": [
          "Application Stages"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:application_stages:list"
            ]
          },
          {
            "bearer": []
          }
        ]
      }
    },
    "/v3/applications/{id}/convert_to_candidate": {
      "post": {
        "summary": "Convert a prospect to a candidate",
        "tags": [
          "Applications"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:applications:convert_to_candidate"
            ]
          },
          {
            "bearer": []
          }
        ]
      }
    },
    "/v3/applications": {
      "post": {
        "summary": "Create application",
        "tags": [
          "Applications"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:applications:create"
            ]
          },
          {
            "bearer": []
          }
        ]
      },
      "get": {
        "summary": "List applications",
        "tags": [
          "Applications"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:applications:list"
            ]
          },
          {
            "bearer": []
          }
        ]
      }
    },
    "/v3/applications/{id}": {
      "delete": {
        "summary": "Delete application",
        "tags": [
          "Applications"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:applications:destroy"
            ]
          },
          {
            "bearer": []
          }
        ]
      },
      "patch": {
        "summary": "Update application",
        "tags": [
          "Applications"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:applications:update"
            ]
          },
          {
            "bearer": []
          }
        ]
      }
    },
    "/v3/applications/{id}/hire": {
      "post": {
        "summary": "Mark an application as hire",
        "tags": [
          "Applications"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:applications:hire"
            ]
          },
          {
            "bearer": []
          }
        ]
      }
    },
    "/v3/applications/{id}/move": {
      "post": {
        "summary": "Move an application to a different stage within the same job or transfer to another job",
        "tags": [
          "Applications"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:applications:move"
            ]
          },
          {
            "bearer": []
          }
        ]
      }
    },
    "/v3/applications/{id}/reject": {
      "post": {
        "summary": "Reject application",
        "tags": [
          "Applications"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:applications:reject"
            ]
          },
          {
            "bearer": []
          }
        ]
      }
    },
    "/v3/applications/{id}/unreject": {
      "post": {
        "summary": "Unreject application",
        "tags": [
          "Applications"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:applications:unreject"
            ]
          },
          {
            "bearer": []
          }
        ]
      }
    },
    "/v3/applied_candidate_tags": {},
    "/v3/applied_candidate_tags/{id}": {},
    "/v3/approval_flows": {},
    "/v3/approval_flows/{id}/replace_approver_groups": {},
    "/v3/approval_flows/{id}/request_approvals": {},
    "/v3/approval_flows/{id}": {},
    "/v3/approver_groups": {},
    "/v3/approver_groups/{id}/replace_approver": {},
    "/v3/approvers": {},
    "/v3/attachments": {},
    "/v3/attachments/{id}": {},
    "/v3/blocked_spam_sources/bulk": {},
    "/v3/blocked_spam_sources": {},
    "/v3/blocked_spam_sources/{id}": {},
    "/v3/bulk_requests": {},
    "/v3/bulk_requests/{bulk_action_uuid}": {
    },
    "/v3/candidate_attribute_types": {},
    "/v3/candidate_educations": {},
    "/v3/candidate_educations/{id}": {},
    "/v3/candidate_employments": {},
    "/v3/candidate_employments/{id}": {},
    "/v3/candidate_tags": {},
    "/v3/candidate_tags/{id}": {},
    "/v3/candidates/{id}/anonymize": {},
    "/v3/candidates": {},
    "/v3/candidates/{id}": {},
    "/v3/candidates/{id}/merge": {},
    "/v3/close_reasons": {},
    "/v3/custom_field_departments": {},
    "/v3/custom_field_departments/{id}": {},
    "/v3/custom_field_offices": {},
    "/v3/custom_field_offices/{id}": {},
    "/v3/custom_field_options": {},
    "/v3/custom_field_options/{id}": {},
    "/v3/custom_field_options/bulk": {},
    "/v3/custom_fields": {},
    "/v3/custom_fields/{id}": {},
    "/v3/default_interviewers": {},
    "/v3/demographic_answer_options": {},
    "/v3/demographic_answers": {},
    "/v3/demographic_question_sets": {},
    "/v3/demographic_questions": {},
    "/v3/departments/bulk": {},
    "/v3/departments": {},
    "/v3/departments/{id}": {},
    "/v3/eeoc": {},
    "/v3/email_templates": {},
    "/v3/focus_candidate_attributes": {},
    "/v3/future_job_permissions": {},
    "/v3/future_job_permissions/{id}": {},
    "/v3/interview_kits": {},
    "/v3/interviewer_tags": {},
    "/v3/interviewers": {},
    "/v3/interviews": {},
    "/v3/interviews/{id}": {},
    "/v3/job_board_custom_locations": {},
    "/v3/job_candidate_attributes": {},
    "/v3/job_hiring_managers": {},
    "/v3/job_hiring_managers/{id}": {},
    "/v3/job_interview_stages": {},
    "/v3/job_interviews": {},
    "/v3/job_notes": {},
    "/v3/job_notes/{id}": {},
    "/v3/job_owners": {},
    "/v3/job_owners/{id}": {},
    "/v3/job_post_locations": {},
    "/v3/job_post_locations/{id}": {},
    "/v3/job_posts": {},
    "/v3/job_posts/{id}": {},
    "/v3/jobs/bulk": {},
    "/v3/jobs": {},
    "/v3/jobs/{id}": {},
    "/v3/notes": {},
    "/v3/offers": {},
    "/v3/offers/{id}": {},
    "/v3/offices/bulk": {},
    "/v3/offices": {},
    "/v3/offices/{id}": {},
    "/v3/openings/bulk": {},
    "/v3/openings": {},
    "/v3/openings/{id}": {},
    "/v3/pay_input_ranges": {
      "get": {
        "summary": "List pay input ranges",
        "tags": [
          "Pay Input Ranges"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:pay_input_ranges:list"
            ]
          },
          {
            "bearer": []
          }
        ]
      }
    },
    "/v3/pay_inputs": {
      "get": {
        "summary": "List pay inputs",
        "tags": [
          "Pay Inputs"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:pay_inputs:list"
            ]
          },
          {
            "bearer": []
          }
        ]
      }
    },
    "/v3/prospect_details": {},
    "/v3/prospect_pool_stages": {},
    "/v3/prospect_pools": {},
    "/v3/referrers": {},
    "/v3/rejection_details": {},
    "/v3/rejection_details/{id}": {},
    "/v3/rejection_reasons": {},
    "/v3/scorecard_candidate_attributes": {},
    "/v3/scorecard_candidate_attributes/{id}": {},
    "/v3/scorecard_question_answer_options": {},
    "/v3/scorecard_question_answers": {},
    "/v3/scorecard_question_answers/{id}": {},
    "/v3/scorecard_question_candidate_attributes": {},
    "/v3/scorecard_question_options": {},
    "/v3/scorecard_questions": {},
    "/v3/scorecards": {
      "get": {
        "summary": "List scorecards",
        "tags": [
          "Scorecards"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:scorecards:list"
            ]
          },
          {
            "bearer": []
          }
        ]
      }
    },
    "/v3/scorecards/{id}": {},
    "/v3/sources": {},
    "/v3/tracking_links": {},
    "/v3/user_emails": {
      "get": {
        "summary": "List user emails",
        "tags": [
          "User Emails"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:user_emails:list"
            ]
          },
          {
            "bearer": []
          }
        ]
      }
    },
    "/v3/user_job_permissions": {
      "get": {
        "summary": "List user job permissions",
        "tags": [
          "User Job Permissions"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:user_job_permissions:list"
            ]
          },
          {
            "bearer": []
          }
        ]
      }
    },
    "/v3/user_job_permissions/{id}": {},
    "/v3/user_roles": {
      "get": {
        "summary": "List user roles",
        "tags": [
          "User Roles"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:user_roles:list"
            ]
          },
          {
            "bearer": []
          }
        ]
      }
    },
    "/v3/users/{id}/activate": {
      "post": {
        "summary": "Activate a user",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:users:activate"
            ]
          },
          {
            "bearer": []
          }
        ]
      }
    },
    "/v3/users/activate/bulk": {
      "post": {
        "summary": "Bulk activate users",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:users:activate"
            ]
          },
          {
            "bearer": []
          }
        ]
      }
    },
    "/v3/users/bulk": {
      "post": {
        "summary": "Bulk create users",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:users:create"
            ]
          },
          {
            "bearer": []
          }
        ]
      },
      "patch": {
        "summary": "Bulk update users",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:users:update"
            ]
          },
          {
            "bearer": []
          }
        ]
      }
    },
    "/v3/users/deactivate/bulk": {
      "post": {
        "summary": "Bulk deactivate users",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:users:deactivate"
            ]
          },
          {
            "bearer": []
          }
        ]
      }
    },
    "/v3/users/revoke_permissions/bulk": {},
    "/v3/users/{id}/deactivate": {
      "post": {
        "summary": "Deactivate a user",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:users:deactivate"
            ]
          },
          {
            "bearer": []
          }
        ]
      }
    },
    "/v3/users": {
      "get": {
        "summary": "List users",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:users:list"
            ]
          },
          {
            "bearer": []
          }
        ]
      },
      "post": {
        "summary": "Create user",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:users:create"
            ]
          },
          {
            "bearer": []
          }
        ]
      }
    },
    "/v3/users/{id}/revoke_permissions": {},
    "/v3/users/{id}": {},
    "/v3/webhooks": {
      "post": {
        "summary": "Create webhook - **Greenhouse partners exclusive**",
        "tags": [
          "Webhooks"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:webhooks:create"
            ]
          },
          {
            "bearer": []
          }
        ]
      }
    },
    "/v3/webhooks/{id}": {
      "delete": {
        "summary": "Delete webhook - **Greenhouse partners exclusive**",
        "tags": [
          "Webhooks"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:webhooks:destroy"
            ]
          },
          {
            "bearer": []
          }
        ]
      },
      "patch": {
        "summary": "Update webhook - **Greenhouse partners exclusive**",
        "tags": [
          "Webhooks"
        ],
        "security": [
          {
            "oauth2": [
              "harvest:webhooks:update"
            ]
          },
          {
            "bearer": []
          }
        ]
      }
    }
  }
}