package reducers

import (
	"errors"
	"fmt"
	"strings"

	"github.com/amp-labs/connectors/scripts/openapi/internal/api/spec"
)

var ErrDuplicateURL = errors.New("duplicate URL")

// ShortestNameFromUrl assigns each schema the shortest object name that uniquely
// identifies its URL.
//
// Names are generated by progressive disambiguation: the last URL segment is
// used initially, and preceding segments are added until all object names are
// unique. Schemas with duplicate URLs are returned with a Problem instead of
// participating in name generation.
func ShortestNameFromUrl(schemas []spec.Schema) []spec.Schema {
	uniqueSchemas, duplicateSchemas := partitionByURL(schemas)
	for i := range duplicateSchemas {
		duplicateSchemas[i].Problem = fmt.Errorf("%w: %s", ErrDuplicateURL, duplicateSchemas[i].UrlPath)
	}

	schemas = uniqueSchemas

	type State struct {
		schema *spec.Schema // need side effects, we modify object name
		parts  []string
		index  int // current position from the right
	}

	states := make([]State, len(schemas))

	for index, schema := range schemas {
		trimmedPath := strings.Trim(schema.UrlPath, "/")
		parts := strings.Split(trimmedPath, "/")
		states[index] = State{
			schema: &schema,
			parts:  parts,
			index:  len(parts) - 1, // start from last segment
		}

		states[index].schema.ObjectName = parts[states[index].index]
	}

	unique := false
	for !unique {
		// Group by current ObjectName
		groups := map[string][]*State{}
		for index := range states {
			groups[states[index].schema.ObjectName] = append(groups[states[index].schema.ObjectName], &states[index])
		}

		unique = true

		for _, group := range groups {
			if len(group) > 1 {
				unique = false

				for _, state := range group {
					// If there are more URI parts increase the ObjectName by adding it as prefix.
					// When index is 0 it means that object name matches full URL (first slash trimmed).
					if state.index > 0 {
						state.index--
						state.schema.ObjectName = state.parts[state.index] + "/" + state.schema.ObjectName
					}
				}
			}
		}
	}

	// Extract final schemas
	result := make([]spec.Schema, len(states))
	for index, state := range states {
		result[index] = *state.schema
	}

	for _, schema := range duplicateSchemas {
		result = append(result, schema)
	}

	return result
}

// ShortestNameFromUrlWithFullFallback assigns each schema an ObjectName based
// on the last segment of its URL path. When multiple schemas produce the same
// name, all colliding schemas use their full URL path, with leading and
// trailing slashes removed, as the ObjectName.
//
// Schemas with duplicate URLs are returned with a Problem and excluded from
// name generation.
func ShortestNameFromUrlWithFullFallback(schemas []spec.Schema) []spec.Schema {
	uniqueSchemas, duplicateSchemas := partitionByURL(schemas)
	for i := range duplicateSchemas {
		duplicateSchemas[i].Problem = fmt.Errorf("%w: %s", ErrDuplicateURL, duplicateSchemas[i].UrlPath)
	}

	schemas = uniqueSchemas

	// Work on copies so we can mutate ObjectName
	result := make([]spec.Schema, len(schemas))
	copy(result, schemas)

	// First pass: assign last segment as ObjectName
	for i := range result {
		parts := strings.Split(strings.Trim(result[i].UrlPath, "/"), "/")
		if len(parts) > 0 {
			result[i].ObjectName = parts[len(parts)-1]
		} else {
			result[i].Problem = errors.New("url is empty after splitting using '/'")
		}
	}

	// Group by ObjectName to detect collisions
	groups := map[string][]int{} // name -> indices in result
	for idx, schema := range result {
		groups[schema.ObjectName] = append(groups[schema.ObjectName], idx)
	}

	// Second pass: for any name that appears more than once, use full URL path
	for _, indices := range groups {
		if len(indices) <= 1 {
			continue
		}
		for _, idx := range indices {
			// Full URL path, trimmed of leading/trailing slashes
			url := result[idx].UrlPath
			result[idx].ObjectName = strings.Trim(url, "/")
		}
	}

	for _, schema := range duplicateSchemas {
		result = append(result, schema)
	}

	return result
}

func partitionByURL(schemas []spec.Schema) (unique, duplicates []spec.Schema) {
	counts := make(map[string]int, len(schemas))

	for _, schema := range schemas {
		url := strings.Trim(schema.UrlPath, "/")
		counts[url]++
	}

	for _, schema := range schemas {
		url := strings.Trim(schema.UrlPath, "/")
		if counts[url] > 1 {
			duplicates = append(duplicates, schema)
		} else {
			unique = append(unique, schema)
		}
	}

	return unique, duplicates
}
