package outreach

import "github.com/amp-labs/connectors/internal/datautils"

// standardObjects lists all known Outreach objects in plural form.
// We use this to decide which names need to be singularized when looking up the schema,
// since the schema uses singular keys. Any object not in this set (e.g. custom objects)
// is looked up as-is.
var standardObjects = datautils.NewStringSet( //nolint:gochecknoglobals
	"accounts",
	"auditLogs",
	"calls",
	"callDispositions",
	"callPurposes",
	"complianceRequests",
	"contentCategories",
	"contentCategoryMemberships",
	"contentCategoryOwnerships",
	"currencyTypes",
	"customDuties",
	"datedConversionRates",
	"duties",
	"emailAddresses",
	"events",
	"favorites",
	"import",
	"mailAliases",
	"mailboxes",
	"mailings",
	"opportunities",
	"opportunityProspectRoles",
	"opportunityStages",
	"personas",
	"phoneNumbers",
	"products",
	"profiles",
	"prospects",
	"purchases",
	"recipients",
	"roles",
	"rulesets",
	"sequences",
	"sequenceStates",
	"sequenceSteps",
	"sequenceTemplates",
	"snippets",
	"stages",
	"tasks",
	"taskDispositions",
	"taskPriorities",
	"taskPurposes",
	"teams",
	"templates",
	"users",
	"webhooks",
)
