@origin=http://localhost:4444

### List ApexClasses (All fields)
# https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_apexclass.htm
GET {{origin}}/services/data/v59.0/query/?q=SELECT+Fields(All)+FROM+ApexClass+Limit+200

### Create ApexClass
POST {{origin}}/services/data/v59.0/sobjects/ApexClass
# Body is set to the script. It is JSON escaped.
Content-Type: application/json

{
  "ApiVersion": 57.0,
  "Status": "Active",
  "Body": "public class GreetingClass2 {public String userName { get; set; }\n\n    public GreetingClass2() {\n\n        userName = 'Guest'; // Default value\n    }\n\n    public String sayHello() {\n        return 'Hello, ' + userName + '!';\n    }\n\n    public void submitName() {\n        // Custom logic to handle the submitted name\n        System.debug('Submitted name: ' + userName);\n    }\n}"
}

### List ApexPages (All fields)
# https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_apexpage.htm
GET {{origin}}/services/data/v59.0/query/?q=SELECT+Fields(All)+FROM+ApexPage+Limit+200

### Create ApexPage
POST {{origin}}/services/data/v59.0/sobjects/ApexPage
# Markup is set to the Visualforce representation of a page. It is JSON escaped.
Content-Type: application/json

{
  "ApiVersion": 57.0,
  "Name": "PageUsingScript2222",
  "MasterLabel": "Create",
  "Markup": "<apex:page controller=\"GreetingClass\"><h1>Hello, {!userName}!</h1><apex:form><apex:inputText value=\"{!userName}\" label=\"Enter your name\"/><apex:commandButton value=\"Submit\" action=\"{!submitName}\"/></apex:form></apex:page>"
}

