name: Build and test
run-name: ${{ github.actor }} is running go build / go test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # git ls-remote https://github.com/actions/checkout.git refs/tags/v7
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Set up Go
        # git ls-remote https://github.com/actions/setup-go.git refs/tags/v7
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
        with:
          go-version: "1.26.5"
          cache: false

      - name: Build
        run: go build -v ./...

      - name: Test
        run: make test
