package loxo

import (
	"github.com/amp-labs/connectors/internal/datautils"
)

var objectsNodePath = datautils.NewDefaultMap(map[string]string{ //nolint:gochecknoglobals
	"activity_types":                 "",
	"address_types":                  "",
	"bonus_payment_types":            "",
	"bonus_types":                    "",
	"company_global_statuses":        "",
	"company_types":                  "",
	"compensation_types":             "",
	"currencies":                     "",
	"deal_workflows":                 "",
	"disability_statuses":            "",
	"diversity_types":                "",
	"dynamic_fields":                 "",
	"education_types":                "",
	"email_types":                    "",
	"equity_types":                   "",
	"ethnicities":                    "",
	"fee_types":                      "",
	"genders":                        "",
	"job_categories":                 "",
	"job_contact_types":              "",
	"job_owner_types":                "",
	"job_statuses":                   "",
	"job_types":                      "",
	"person_global_statuses":         "",
	"person_lists":                   "",
	"person_share_field_types":       "",
	"person_types":                   "",
	"phone_types":                    "",
	"pronouns":                       "",
	"question_types":                 "",
	"scorecard_recommendation_types": "",
	"scorecard_types":                "",
	"scorecard_visibility_types":     "",
	"seniority_levels":               "",
	"social_profile_types":           "",
	"users":                          "",
	"veteran_statuses":               "",
	"workflow_stages":                "",
	"workflows":                      "",
	"companies":                      "companies",
	"countries":                      "countries",
	"deals":                          "deals",
	"email_tracking":                 "tracking",
	"form_templates":                 "form_templates",
	"forms":                          "forms",
	"jobs":                           "results",
	"people":                         "people",
	"people/emails":                  "person_emails",
	"people/phones":                  "person_phones",
	"person_events":                  "person_events",
	"placements":                     "placements",
	"schedule_items":                 "schedule_items",
	"scorecards":                     "scorecards",
	"sms":                            "sms",
	"source_types":                   "source_types",
}, func(objectName string) string {
	return objectName
},
)

var objectWithPrefixValue = datautils.NewSet( //nolint:gochecknoglobals
	"scorecard_recommendation_types",
	"scorecard_types",
	"scorecard_templates",
	"scorecard_visibility_types ",
)
